### Настройки вывода

[Pandas docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html)

In [3]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Python_ITMO_2025/Занятие 5 - 07.10.2025/laptops_10.csv')

In [9]:
df.head(100)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,FlashStorage
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Acer,Spin 5,2 in 1 Convertible,13.3,Intel Core i5 8250U 1.6GHz,8GB,Intel UHD Graphics 620,Windows 10,1.50,847.00,Intel,256,SSD
96,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Linux,2.20,599.90,Intel,1024,HDD
97,Dell,Inspiron 3567,Notebook,15.6,Intel Core i3 6006U 2GHz,4GB,AMD Radeon R5 M430,Linux,2.20,485.00,Intel,256,SSD
98,Asus,X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Nvidia GeForce 920M,Windows 10,2.00,577.00,Intel,256,SSD
99,HP,Omen 15-ce007nv,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,12GB,Nvidia GeForce GTX 1050,Windows 10,2.62,1249.00,Intel,128,HDD

In [11]:
pd.options.display.max_rows

60

In [12]:
pd.options.display.max_rows = 100

pd.options.display.max_rows

100

In [14]:
df.head(10)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,FlashStorage
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD
5,Acer,Aspire 3,Notebook,15.6,AMD A9-Series 9420 3GHz,4GB,AMD Radeon R5,Windows 10,2.10,400.00,AMD,500,HDD
6,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.2GHz,16GB,Intel Iris Pro Graphics,Mac OS X,2.04,2139.97,Intel,256,FlashStorage
7,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,1158.70,Intel,256,FlashStorage
8,Asus,ZenBook UX430UN,Ultrabook,14.0,Intel Core i7 8550U 1.8GHz,16GB,Nvidia GeForce MX150,Windows 10,1.30,1495.00,Intel,512,SSD
9,Acer,Swift 3,Ultrabook,14.0,Intel Core i5 8250U 1.6GHz,8GB,Intel UHD Graphics 620,Windows 10,1.60,770.00,Intel,256,SSD

In [15]:
pd.set_option("max_colwidth", 10)

In [16]:
df

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBoo...,Ultrabook,13.3,Intel ...,8GB,Intel ...,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macboo...,Ultrabook,13.3,Intel ...,8GB,Intel ...,macOS,1.34,898.94,Intel,128,FlashS...
2,HP,250 G6,Notebook,15.6,Intel ...,8GB,Intel ...,No OS,1.86,575.00,Intel,256,SSD
3,Apple,MacBoo...,Ultrabook,15.4,Intel ...,16GB,AMD Ra...,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBoo...,Ultrabook,13.3,Intel ...,8GB,Intel ...,macOS,1.37,1803.60,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,Yoga 5...,2 in 1...,14.0,Intel ...,4GB,Intel ...,Window...,1.80,638.00,Intel,128,SSD
1299,Lenovo,Yoga 9...,2 in 1...,13.3,Intel ...,16GB,Intel ...,Window...,1.30,1499.00,Intel,512,SSD
1300,Lenovo,IdeaPa...,Notebook,14.0,Intel ...,2GB,Intel ...,Window...,1.50,229.00,Intel,64,FlashS...
1301,HP,15-AC1...,Notebook,15.6,Intel ...,6GB,AMD Ra...,Window...,2.19,764.00,Intel,1024,HDD
1302,Asus,X553SA...,Notebook,15.6,Intel ...,4GB,Intel ...,Window...,2.20,369.00,Intel,500,HDD

In [17]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 10]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 100]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. Defaults to False,
    unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
    (if set to "1" for True, needs to be set before pandas is imported).
    [default: False] [currently: False]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
    (Deprecated, use `` instead.)
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype. This option is ignored if
    ``future.infer_string`` is set to True.
    [default: python] [currently: python]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).

    This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        1303 non-null   object
 1   Product        1303 non-null   object
 2   TypeName       1303 non-null   object
 3   Inches         1303 non-null   float64
 4   Cpu            1303 non-null   object
 5   Ram            1303 non-null   object
 6   Gpu            1303 non-null   object
 7   OpSys          1303 non-null   object
 8   Weight         1303 non-null   float64
 9   Price_euros    1303 non-null   float64
 10  Cpu_Company    1303 non-null   object
 11  Memory_Amount  1303 non-null   int64
 12  Memory_Type    1303 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 132.5+ KB

In [22]:
display_settings = {
    'max_columns': 10,
    'colheader_justify': 'left',
    'large_repr': 'info'
}

for op, value in display_settings.items():
    pd.set_option(f"display.{op}", value)

In [23]:
# display_settings.items()

In [24]:
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        1303 non-null   object
 1   Product        1303 non-null   object
 2   TypeName       1303 non-null   object
 3   Inches         1303 non-null   float64
 4   Cpu            1303 non-null   object
 5   Ram            1303 non-null   object
 6   Gpu            1303 non-null   object
 7   OpSys          1303 non-null   object
 8   Weight         1303 non-null   float64
 9   Price_euros    1303 non-null   float64
 10  Cpu_Company    1303 non-null   object
 11  Memory_Amount  1303 non-null   int64
 12  Memory_Type    1303 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 132.5+ KB

In [25]:
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        5 non-null      object
 1   Product        5 non-null      object
 2   TypeName       5 non-null      object
 3   Inches         5 non-null      float64
 4   Cpu            5 non-null      object
 5   Ram            5 non-null      object
 6   Gpu            5 non-null      object
 7   OpSys          5 non-null      object
 8   Weight         5 non-null      float64
 9   Price_euros    5 non-null      float64
 10  Cpu_Company    5 non-null      object
 11  Memory_Amount  5 non-null      int64
 12  Memory_Type    5 non-null      object
dtypes: float64(3), int64(1), object(9)
memory usage: 652.0+ bytes

In [26]:
pd.reset_option('large_repr')

In [27]:
df

,Company,Product,TypeName,Inches,Cpu,...,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBoo...,Ultrabook,13.3,Intel ...,...,1.37,1339.69,Intel,128,SSD
1,Apple,Macboo...,Ultrabook,13.3,Intel ...,...,1.34,898.94,Intel,128,FlashS...
2,HP,250 G6,Notebook,15.6,Intel ...,...,1.86,575.00,Intel,256,SSD
3,Apple,MacBoo...,Ultrabook,15.4,Intel ...,...,1.83,2537.45,Intel,512,SSD
4,Apple,MacBoo...,Ultrabook,13.3,Intel ...,...,1.37,1803.60,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,Yoga 5...,2 in 1...,14.0,Intel ...,...,1.80,638.00,Intel,128,SSD
1299,Lenovo,Yoga 9...,2 in 1...,13.3,Intel ...,...,1.30,1499.00,Intel,512,SSD
1300,Lenovo,IdeaPa...,Notebook,14.0,Intel ...,...,1.50,229.00,Intel,64,FlashS...
1301,HP,15-AC1...,Notebook,15.6,Intel ...,...,2.19,764.00,Intel,1024,HDD
1302,Asus,X553SA...,Notebook,15.6,Intel ...,...,2.20,369.00,Intel,500,HDD

In [28]:
pd.set_option("display.max_info_columns", 200)

In [ ]:
# # pandas
# pd.set_option("display.max_columns", None)      # показывать все столбцы
# pd.set_option("display.max_rows", 100)          # сколько строк максимум показывать
# pd.set_option("display.width", 1200)            # ширина вывода
# pd.set_option("display.max_colwidth", 200)      # ширина текста в ячейке
# pd.set_option("display.float_format", "{:.2f}".format)  # формат float

# # matplotlib
# plt.rcParams["figure.figsize"] = (8, 5)         # размер графиков по умолчанию
# plt.rcParams["figure.dpi"] = 120                # качество
# plt.rcParams["font.size"] = 11                  # размер шрифта
# plt.rcParams["axes.titlesize"] = 13             # заголовок графика
# plt.rcParams["axes.labelsize"] = 11             # подписи осей
# plt.rcParams["xtick.labelsize"] = 10
# plt.rcParams["ytick.labelsize"] = 10
# plt.rcParams["legend.fontsize"] = 10

# # стиль графиков
# plt.style.use("default")

### Warnings

In [29]:
import warnings
warnings.warn("Это предупреждение!")

/tmp/ipykernel_279/2856871940.py:2: UserWarning: Это предупреждение!
  warnings.warn("Это предупреждение!")

In [ ]:
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
warnings.filterwarnings("ignore")

### Настройка темы ноутбука
[ссылка](https://www.geeksforgeeks.org/how-to-change-the-theme-in-jupyter-notebook/)

In [ ]:
# !pip install jupyterthemes

In [ ]:
!jt -l

Available Themes:
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl

In [ ]:
!jt -t onedork

In [ ]:
!jt -r

Reset css and font defaults in:
C:\Users\Dasha\.jupyter\custom &
C:\Users\Dasha\AppData\Roaming\jupyter\nbextensions

### Настройка вывода таблицы

In [30]:
df = pd.DataFrame(np.random.normal(size=(6,6)), columns=[x for x in "ABCDEF"])
df

   A         B         C         D         E         F
0  0.203441 -1.579559  0.076420  2.270737  1.459605  0.576294
1 -0.493965 -0.950349  1.612466 -0.232065  0.158511 -1.676749
2 -0.295816 -0.367696 -0.860680  2.023045 -1.187149 -0.417573
3  0.675255  1.599868  0.171656 -0.878916  0.836571 -0.137732
4 -0.458623 -0.337565 -1.120269  0.041328 -1.401812 -0.610949
5  0.261927 -0.006816  0.230570 -0.587268 -0.361588  1.475556

In [33]:
def neg_red(x):
    return f"color: {'red' if x < 0 else 'green'}"

# df.style.applymap(neg_red)

df.style.applymap(lambda x: f"color: {'red' if x < 0 else 'black'}")

/tmp/ipykernel_279/3269217224.py:6: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(lambda x: f"color: {'red' if x < 0 else 'black'}")

In [34]:
def gold_max(xs):
    m = xs.to_numpy().max()
    color = {True: "background-color: #c78f2e", False: ""}
    is_max = (xs == m).replace(color)
    return is_max

In [43]:
df.style.apply(gold_max, axis=None)

In [44]:
df.style.background_gradient(cmap="magma")

In [48]:
df.abs().style.bar(align="left", width=90)

In [49]:
head = {"selector": "th", "props": [("text-align", "center")]}
df.style.set_table_styles([head]).bar(align="mid", color=['red', 'green'], vmin=-3, vmax=3)

In [50]:
df.style.bar(align="mid", width=50).apply(gold_max, axis=None).applymap(neg_red)

/tmp/ipykernel_279/3665736045.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.bar(align="mid", width=50).apply(gold_max, axis=None).applymap(neg_red)