In [3]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
data = pd.read_csv('/content/drive/MyDrive/Python_ITMO_2025/Занятие 5 - 07.10.2025/Verizon.csv', sep=';')
data.head()

,longdist,internat,local,int_disc,billtype,pay,age,gender,marital,children,income,churn
0,8.62,NaN,8.49,Нет,Бюджетный,CH,43.0,Мужской,_Женат,0.0,33935.8,0
1,21.27,0.0,"218,12",Нет,Бюджетный,CH,60.0,NaN,_Одинокий,2.0,"95930,6",1
2,"6,13",0.0,NaN,Да,NaN,NaN,25.0,Женский,NaN,2.0,"295,34",1
3,16.46,0.0,"57,66",Да,Бесплатный,NaN,93.0,Женский,Одинокий,0.0,NaN,1
4,NaN,0.0,"16,01",Да,Бесплатный,CC,68.0,Женский&*,NaN,0.0,"99832,9",1

In [5]:
data.shape

(1477, 12)

In [8]:
data.duplicated().sum()

np.int64(2)

In [13]:
data[data.duplicated(subset=['longdist', 'billtype'])]

,longdist,internat,local,int_disc,billtype,pay,age,gender,marital,children,income,churn
11,NaN,0.0,3.42,Нет,Бесплатный,CC,26.0,Мужской,Женат,0.0,10095.8,1
74,0.0,0.0,1.38,Нет,Бесплатный,CC,64.0,Мужской,Женат,1.0,56360.5,1
79,0.0,0.0,4.83,Нет,Бесплатный,CC,59.0,Мужской,Одинокий,0.0,60111.8,1
84,0.0,0.0,2.02,Нет,Бесплатный,CC,25.0,Женский,Одинокий,0.0,30094.6,1
92,0.0,0.0,0.36,Нет,Бюджетный,CC,25.0,Мужской,Женат,0.0,4545.11,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1467,0.0,0.0,1.18,Да,Бюджетный,CC,79.0,Мужской,Одинокий,2.0,89566.2,1
1470,0.0,0.0,4.76,Нет,Бесплатный,CC,27.0,Женский,Женат,0.0,50290.7,1
1474,0.0,0.0,1.65,Нет,Бесплатный,Auto,88.0,Женский,Женат,2.0,80326.6,1
1475,12.86,0.04,156.51,Да,Бюджетный,CC,18.0,Женский,Женат,0.0,13441.5,0
1476,14.77,0.0,30.42,Нет,Бесплатный,CH,86.0,Мужской,Женат,0.0,92167.3,0

In [14]:
data.drop_duplicates(subset=None, keep='first',
                     inplace=True)

,longdist,internat,local,int_disc,billtype,pay,age,gender,marital,children,income,churn
0,8.62,NaN,8.49,Нет,Бюджетный,CH,43.0,Мужской,_Женат,0.0,33935.8,0
1,21.27,0.0,"218,12",Нет,Бюджетный,CH,60.0,NaN,_Одинокий,2.0,"95930,6",1
2,"6,13",0.0,NaN,Да,NaN,NaN,25.0,Женский,NaN,2.0,"295,34",1
3,16.46,0.0,"57,66",Да,Бесплатный,NaN,93.0,Женский,Одинокий,0.0,NaN,1
4,NaN,0.0,"16,01",Да,Бесплатный,CC,68.0,Женский&*,NaN,0.0,"99832,9",1
...,...,...,...,...,...,...,...,...,...,...,...,...
1472,25.46,0.0,43.91,Да,Бесплатный,Auto,46.0,Мужской,Женат,0.0,10689.4,0
1473,8.46,0.0,22.65,Нет,Бесплатный,CC,51.0,Женский,Одинокий,2.0,2638.11,1
1474,0.0,0.0,1.65,Нет,Бесплатный,Auto,88.0,Женский,Женат,2.0,80326.6,1
1475,12.86,0.04,156.51,Да,Бюджетный,CC,18.0,Женский,Женат,0.0,13441.5,0
1476,14.77,0.0,30.42,Нет,Бесплатный,CH,86.0,Мужской,Женат,0.0,92167.3,0

In [ ]:
data[data.duplicated(keep=False)]

Empty DataFrame
Columns: [longdist, internat, local, int_disc, billtype, pay, age, gender, marital, children, income, churn]
Index: []

In [ ]:
data.shape

(1475, 12)